name = "gzlib"
version = "1.0.0"

description = "zlib utilities for Gleam"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "LilyRose2798", repo = "gzlib" }
links = [
  { title = "7Circles Git", href = "https://git.7cs.dev/lily/gzlib" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
